intern-crm-web/src/main/webapp/view/login.jsp

change login

---

intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/login.jsp

"tile3 done"

---

intern-crm-web/src/main/java/com/smartdev/controller/HomePageController.java
intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/homeSeller.jsp

homeseller

---

intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/homeSeller.jsp

homeseller1

---

intern-crm-web/pom.xml
intern-crm-web/src/main/java/com/smartdev/controller/CustomerPageController.java
intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/addcustomer.jsp

add customer

---

crm-services/src/main/java/com/smartdev/crm/service/SellerDetailService.java
crm-services/src/main/java/com/smartdev/crm/service/SellerDetailServiceImpl.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/ManageSellerController.java
intern-crm-web/src/main/webapp/WEB-INF/appconfig-data.xml

"List seller - change package"

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/RoleRepository.java
crm-services/src/main/java/com/smartdev/crm/service/RoleService.java
crm-services/src/main/java/com/smartdev/crm/service/RoleServiceImpl.java
crm-services/src/main/java/com/smartdev/crm/service/UserService.java
crm-services/src/main/java/com/smartdev/crm/service/UserServiceImpl.java
crm_model/src/main/java/com/smartdev/user/entity/User.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/ManageSellerController.java
intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/create-seller.jsp
intern-crm-web/src/main/webapp/view/list-seller.jsp

"Create seller"

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/CustomerRepository.java
crm-dao/src/main/java/com/smartdev/user/dao/repository/HistoryAdvisoryRepository.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerService.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerServiceImpl.java
crm-services/src/main/java/com/smartdev/crm/service/HistoryAdvisoryService.java
crm-services/src/main/java/com/smartdev/crm/service/HistoryAdvisoryServiceImpl.java
crm_model/src/main/java/com/smartdev/user/entity/Customer.java
intern-crm-web/src/main/java/com/smartdev/controller/seller/ListCustomerController.java
intern-crm-web/src/main/webapp/view/advisory.jsp
intern-crm-web/src/main/webapp/view/list-custom-seller.jsp

show advisory

---

crm_model/src/main/java/com/smartdev/user/entity/User.java

"Create Seller fix validation "

---

crm-services/src/main/java/com/smartdev/crm/service/user/UserServiceImpl.java
intern-crm-web/src/main/webapp/view/list-seller.jsp

also show status isDelete and modify the method check exist

"modify list seller and create account"

---

intern-crm-web/src/main/webapp/view/addcustomer.jsp
intern-crm-web/src/main/webapp/view/list-custom-seller.jsp

"Fix UI add a customer"

---

intern-crm-web/src/main/webapp/view/list-custom-seller.jsp

hiển thị ngày tạo customer trên list

[Front end] hiển thị ngày tạo khách hàng trên list

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/CustomerRepository.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerService.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerServiceImpl.java
intern-crm-web/src/main/java/com/smartdev/controller/seller/HomePageSellerController.java
intern-crm-web/src/main/resources/application.properties
intern-crm-web/src/main/resources/database.properties
intern-crm-web/src/main/webapp/view/advisory.jsp
intern-crm-web/src/main/webapp/view/list-custom-seller.jsp

UI advisory and list customer for seller

UI advisory and list customer for seller

---

intern-crm-web/src/main/java/com/smartdev/controller/LoginController.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/HomePageManagerController.java
intern-crm-web/src/main/java/com/smartdev/controller/seller/HomePageSellerController.java
intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/template/layout/header.jsp
intern-crm-web/src/main/webapp/view/update-manager-account.jsp

"Update manager account "

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/CustomerRepository.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerService.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerServiceImpl.java
intern-crm-web/src/main/java/com/smartdev/controller/SearchController.java
intern-crm-web/src/main/webapp/view/list-custom-manage.jsp
intern-crm-web/src/main/webapp/view/list-custom-seller.jsp

search customer

---

intern-crm-web/src/main/java/com/smartdev/controller/LoginController.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/CampainController.java
intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/campain-customer.jsp
intern-crm-web/src/main/webapp/view/campain-manager.jsp
intern-crm-web/src/main/webapp/view/campain.jsp
intern-crm-web/src/main/webapp/view/template/layout/menu-manager.jsp

"All UI campain"

---

crm-services/src/main/java/com/smartdev/crm/service/CustomerCampaignService.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerCampaignServiceImpl.java
crm-services/src/main/java/com/smartdev/crm/service/helper/Converter.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/CampaignController.java
intern-crm-web/src/main/webapp/view/campaign-customer.jsp

"Move to crm"

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/CampaignRepository.java
crm-services/src/main/java/com/smartdev/crm/service/CampaignService.java
crm-services/src/main/java/com/smartdev/crm/service/CampaignServiceImpl.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/CampaignController.java
intern-crm-web/src/main/webapp/view/campaign-manager.jsp

search compaign

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/CustomerRepository.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerService.java
crm-services/src/main/java/com/smartdev/crm/service/CustomerServiceImpl.java
crm-services/src/main/java/com/smartdev/crm/service/StatusService.java
crm-services/src/main/java/com/smartdev/crm/service/StatusServiceImpl.java
intern-crm-web/src/main/java/com/smartdev/controller/BlocklistController.java
intern-crm-web/src/main/java/com/smartdev/controller/SearchController.java
intern-crm-web/src/main/webapp/WEB-INF/title3.xml
intern-crm-web/src/main/webapp/view/blocklist.jsp
intern-crm-web/src/main/webapp/view/searchblock.jsp

search, show block list

---

crm-dao/src/main/java/com/smartdev/user/dao/repository/CampaignRepository.java
crm-services/src/main/java/com/smartdev/crm/service/CampaignService.java
crm-services/src/main/java/com/smartdev/crm/service/CampaignServiceImpl.java
intern-crm-web/src/main/java/com/smartdev/controller/manager/CampaignController.java
intern-crm-web/src/main/webapp/view/campaign-manager.jsp

edit search compaign

---

intern-crm-web/src/main/webapp/view/list-seller.jsp

"fix missing add seller button"
